### ISSUE TITLE
Remove positional CSS

### ISSUE THREAD

**Issue by yuchi** [substance/substance-legacy#290]
Because we're dealing with a guaranteed WebKit why don't we move from positional CSS to language-specific CSS, this could solve a lot of problems for #289. 

Actually this means that:

``` css
.selector {
  margin-top: 0em;
  margin-right: 0em;
  margin-bottom: 0em;
  margin-left: 0em;
}
```

Becomes

``` css
.selector {
  -webkit-margin-before: 0em; /* top */
  -webkit-margin-start: 0em; /* left on ltr, right on rtl */
  -webkit-margin-after: 0em; /* bottom */
  -webkit-margin-end: 0em; /* right on ltr, left on rtl */
}
```

AFAIK exists similar values for `float`.

**Comment by yuchi** [comment]
BTW, if we can assume that every "margin-left" is actually a "-webkit-margin-start" we can easily make the translation automatic.

**Comment by michael** [comment]
Not aware of what the exact differences are. But sounds like a good idea if it helps us. :)

**Comment by yuchi** [comment]
In RTL languages (hebrew, for instance) "left" and "right" switch value. For that margin-left and margin-right are not enough precise. In single language context (web) we usually do the following (given that `L` is the i18n util):

``` ejs
<html class="<%= L('language-direction', 'ltr') %>">
  ...
</html>
```

And then in CSS:

``` css
.cool-style {
  background: red;
  margin-right: 3em;
}

.rtl .cool-style {
  margin-right: 0em;
  margin-left: 3em;
}
```

or, when you work with CSS maniacs like me:

``` css
.cool-style {
  background: red;
}

.ltr .cool-style {
  margin-right: 3em;
}

.rtl .cool-style {
  margin-left: 3em;
}
```

This in fact poses to major issues:
1. You need to be extremely accurate with cascading, after all you're adding a class there!
2. No support for bidirectional contexts.

Point 2 is the most critical. While we can query (CSS) for `[dir="rtl"]`, it is not inherited by children elements, and that means that you cannot automatically give the correct position.

---

I don't know if there's any WebKit-specific solution for paddings, floats and similar. I'll investigate.

**EDIT**: -webkit-padding-\* are there
